---
title: "Untitled"
output: html_document
---



```{r}
library(ggplot2)
library(RColorBrewer)
library(gridExtra)
library(openxlsx)

```


# hyper-parameter tuning

```{r}
## layers
# cifar100-n30
plot_data_layer = data.frame(layer = as.character(c(1, 3, 6, 9, 12, 15)),
                             setting = rep(c("S = 5", "S = 10", "S = 30"), each = 6),
                       acc = c(0.1043, 0.1178, 0.1078, 0.1418, 0.1563, 0.6822,
                               0.2967, 0.3506, 0.4219, 0.5258, 0.3887, 0.6561,
                         0.4433,0.4601,0.4683,0.5412, 0.5725,0.6100))
plot_data_layer$layer = factor(plot_data_layer$layer, levels = as.character(c(1, 3, 6, 9, 12, 15)))
plot_data_layer$setting = factor(plot_data_layer$setting, levels = c("S = 5", "S = 10", "S = 30"))

p1 = ggplot(plot_data_layer, aes(x = layer, y = acc, color = setting, group = setting)) + #, shape = setting
  geom_point(shape = 9, size = 3) +
  geom_line(size = 1) +
  labs(y = "Accuracy (Acc)") + #, title = "CIFAR100"
  theme_bw(base_size = 20) +
  theme(
    plot.title = element_text(hjust=0.5),
    legend.text = element_text(hjust=0),
    legend.title = element_text(hjust=0.5),
    legend.position = "top", 
  )


## tau ------------------------------------------
tao_cifar100_n5 = data.frame(tao = c('25', '50','75', '+infinity'),
                              acc = c(0.602, 0.6792, 0.6883, 0.7223))
tao_cifar100_n10 = data.frame(tao = c('25', '50','75', '+infinity'),
                              acc = c(0.2739, 0.4254, 0.4814, 0.6886))
tao_cifar100_n30 = data.frame(tao = c('25', '50','75', '+infinity'),
                              acc = c(0.5747, 0.6066, 0.6231, 0.6072))


tao_df = rbind(tao_cifar100_n5, tao_cifar100_n10, tao_cifar100_n30)

tao_df$Setting = c(rep("S = 5", 4),
                   rep("S = 10", 4),
                   rep("S = 30", 4))
tao_df$Setting = factor(tao_df$Setting, levels = c("S = 5", "S = 10", "S = 30"))
tao_df$tao = factor(tao_df$tao, levels = c('25', '50', '75','+infinity'))


p3 = ggplot(tao_df, aes(x = tao, y = acc, group = Setting, colour = Setting)) + #, shape = setting
  geom_line(size = 1) +
  geom_point(size = 3, shape = 19) + # shape = 10, 
  geom_point(aes(x = '+infinity', y = 0.7223), shape = 15, size = 3, color = "#FFC000")+
  geom_point(aes(x = '+infinity', y = 0.6886), shape = 15, size = 3, color = "#FFC000") +
  geom_point(aes(x = '75', y = 0.6231), shape = 15, size = 3, color = "#FFC000") +
  scale_x_discrete(labels = expression('25', '50', '75', +infinity)) +
  labs(y = "Accuracy (Acc)", x = expression(tau[L])) + 
  theme_bw(base_size = 20) +
  theme(
    plot.title = element_text(hjust=0.5),
    legend.text = element_text(hjust=0),
    legend.title = element_text(hjust=0.5),
    legend.position = "top",
  )

g <- arrangeGrob(p1, p3, ncol=3) #generates g
ggsave(file='1.png', g, width = 18, height = 6)


SaveDR <- c("./plot/")
png(filename = paste0(SaveDR,"param-tuning",".png"), width = 1000, height = 500)

grid.arrange(p1, p3,  ncol = 2)

dev.off()


```

# convergence

# cifar100

```{r}
path = "./cifar100/convergence_loss.xlsx"
data <- read.xlsx(xlsxFile = path, sheet = 1, skipEmptyRows = FALSE)


plot_data1 = data.frame(rounds = c(1:470), method = rep(c("FedAvg", "FedFac"), each = 470), acc = c(data[31:500,1], data[31:500,2]))

p1 = ggplot(plot_data1, aes(x = rounds, y = acc, color = method)) +
  geom_line() +
  labs(y = "Training Loss", title = expression(paste("CIFAR100: ", S == 5))) +
  scale_color_manual(values = c("#2BB07FFF", "#FFC000")) +
  guides(colour=guide_legend(title=NULL)) + 
  scale_x_continuous(breaks = c(0, 95, 95*2, 95*3, 95*4, 477), labels = c("0","100","200","300","400","500")) +
  theme_bw(base_size = 20) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linetype = "solid"),
    plot.title = element_text(hjust=0.5),
    legend.position = c(.95, .7),
    legend.justification = c("right", "bottom"),
    legend.box.background = element_rect(color = "gray"),
    legend.key = element_blank()
  )


plot_data1 = data.frame(rounds = c(1:500), method = rep(c("FedAvg", "FedFac"), each = 500), acc = c(data[1:500,3], data[1:500,8]))

p2 = ggplot(plot_data1, aes(x = rounds, y = acc, color = method)) +
  geom_line() +
  labs(y = "Training Loss", title = expression(paste("CIFAR100: ", S == 10))) +
  scale_color_manual(values = c("#2BB07FFF", "#FFC000")) +
  guides(colour=guide_legend(title=NULL)) + 
  theme_bw(base_size = 20) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linetype = "solid"),
    plot.title = element_text(hjust=0.5),
    legend.position = c(.95, .7),
    legend.justification = c("right", "bottom"),
    legend.box.background = element_rect(color = "gray"),
    legend.key = element_blank()
  )


plot_data1 = data.frame(rounds = c(1:500), method = rep(c("FedAvg", "FedFac"), each = 500), acc = c(data[1:500,5], data[1:500,6]))

p3 = ggplot(plot_data1, aes(x = rounds, y = acc, color = method)) +
  geom_line() +
  labs(y = "Training Loss", title = expression(paste("CIFAR100: ", S == 30))) +
  scale_color_manual(values = c("#2BB07FFF", "#FFC000")) +
  guides(colour=guide_legend(title=NULL)) + 
  theme_bw(base_size = 20) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linetype = "solid"),
    plot.title = element_text(hjust=0.5),
    legend.position = c(.95, .7),
    legend.justification = c("right", "bottom"),
    legend.box.background = element_rect(color = "gray"),
    legend.key = element_blank()
  )



```

# cifar10

```{r}
path = "./cifar/result/resnet/pretrain/convergence_loss.xlsx"
data <- read.xlsx(xlsxFile = path, sheet = 1, skipEmptyRows = FALSE)


plot_data1 = data.frame(rounds = c(1:500), method = rep(c("FedAvg", "FedFac"), each = 500), loss = c(data[1:500,1], data[1:500,2]))

cifar10_01 = ggplot(plot_data1, aes(x = rounds, y = loss, color = method)) +
  geom_line() +
  labs(y = "Training Loss", title = expression(paste("CIFAR10: ", pi == 0.1))) +
  scale_color_manual(values = c("#2BB07FFF", "#FFC000")) +
  guides(colour=guide_legend(title=NULL)) + 
  theme_bw(base_size = 20) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linetype = "solid"),
    plot.title = element_text(hjust=0.5),
    legend.position = c(.95, .7),
    legend.justification = c("right", "bottom"),
    legend.box.background = element_rect(color = "gray"),
    legend.key = element_blank()
  )


plot_data1 = data.frame(rounds = c(1:250), method = rep(c("FedAvg", "FedFac"), each = 250), loss = c(data[1:250,3], data[1:250,4]))

cifar10_001 = ggplot(plot_data1, aes(x = rounds, y = loss, color = method)) +
  geom_line() +
  labs(y = "Training Loss", title = expression(paste("CIFAR10: ", pi == 0.01))) +
  scale_color_manual(values = c("#2BB07FFF", "#FFC000")) +
  guides(colour=guide_legend(title=NULL)) + 
  theme_bw(base_size = 20) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linetype = "solid"),
    plot.title = element_text(hjust=0.5),
    legend.position = c(.95, .7),
    legend.justification = c("right", "bottom"),
    legend.box.background = element_rect(color = "gray"),
    legend.key = element_blank()
  )


plot_data1 = data.frame(rounds = c(1:300), method = rep(c("FedAvg", "FedFac"), each = 300), loss = c(data[1:300,5], data[1:300,6]))

cifar10_05 = ggplot(plot_data1, aes(x = rounds, y = loss, color = method)) +
  geom_line() +
  labs(y = "Training Loss", title = expression(paste("CIFAR10: ", pi == 0.5))) +
  scale_color_manual(values = c("#2BB07FFF", "#FFC000")) +
  guides(colour=guide_legend(title=NULL)) + 
  theme_bw(base_size = 20) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linetype = "solid"),
    plot.title = element_text(hjust=0.5),
    legend.position = c(.95, .7),
    legend.justification = c("right", "bottom"),
    legend.box.background = element_rect(color = "gray"),
    legend.key = element_blank()
  )

#
plot_data1 = data.frame(rounds = c(1:300), method = rep(c("FedAvg", "FedFac"), each = 300), loss = c(data[1:300,7], data[1:300,8]))

cifar10_1 = ggplot(plot_data1, aes(x = rounds, y = loss, color = method)) +
  geom_line() +
  labs(y = "Training Loss", title = expression(paste("CIFAR10: ", pi == 1))) +
  scale_color_manual(values = c("#2BB07FFF", "#FFC000")) +
  guides(colour=guide_legend(title=NULL)) + 
  theme_bw(base_size = 20) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linetype = "solid"),
    plot.title = element_text(hjust=0.5),
    legend.position = c(.95, .7),
    legend.justification = c("right", "bottom"),
    legend.box.background = element_rect(color = "gray"),
    legend.key = element_blank()
  )

```

# femnist 

```{r}
path = "./femnist/ep20_client107/loss.xlsx"
data <- read.xlsx(xlsxFile = path, sheet = 1, skipEmptyRows = FALSE)

plot_data1 = data.frame(rounds = c(1:500), method = rep(c("FedAvg", "FedFac"), each = 500), loss = c(data[1:500,1], data[1:500,2]))

femnist = ggplot(plot_data1, aes(x = rounds, y = loss, color = method)) +
  geom_line() +
  labs(y = "Training Loss", title = "FEMNIST") +
  scale_color_manual(values = c("#2BB07FFF", "#FFC000")) +
  guides(colour=guide_legend(title=NULL)) + 
  theme_bw(base_size = 20) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linetype = "solid"),
    plot.title = element_text(hjust=0.5),
    legend.position = c(.95, .7),
    legend.justification = c("right", "bottom"),
    legend.box.background = element_rect(color = "gray"),
    legend.key = element_blank()
  )

```

# shakespeare

```{r}
path = "./shakespeare/result/loss.xlsx"
data <- read.xlsx(xlsxFile = path, sheet = 1, skipEmptyRows = FALSE)

plot_data1 = data.frame(rounds = c(1:100), method = rep(c("FedAvg", "FedFac"), each = 100), loss = c(data[,1], data[,2]))

shakespeare = ggplot(plot_data1, aes(x = rounds, y = loss, color = method)) +
  geom_line() +
  labs(y = "Training Loss", title = "Shakespeare") +
  scale_color_manual(values = c("#2BB07FFF", "#FFC000")) +
  guides(colour=guide_legend(title=NULL)) + 
  theme_bw(base_size = 20) +
  theme(
    panel.background = element_rect(fill = "white", colour = "black", linetype = "solid"),
    plot.title = element_text(hjust=0.5),
    legend.position = c(.95, .7),
    legend.justification = c("right", "bottom"),
    legend.box.background = element_rect(color = "gray"),
    legend.key = element_blank()
  )

```


```{r}
SaveDR <- c("./plot/")
png(filename = paste0(SaveDR,"loss-convergence4",".png"), width = 1500, height = 1500)

grid.arrange(cifar10_001,cifar10_01, cifar10_05, cifar10_1, p1, p2, p3, femnist,shakespeare, ncol = 3)

dev.off()

```

